# DataSource Config
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-handlers-package: com.example.markdown_demo.common.typehandler

spring:
  web:
    resources:
      static-locations: classpath:templates/
  codec:
    max-in-memory-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notebook?useUnicode=true&useSSL=false&character_set_server=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 150MB

file:
  upload:
    path: /staticFile/upload

server:
  port: 8090
  host: localhost

deepbricks:
  api:
    url: https://api.deepbricks.ai/v1/chat/completions
    key: sk-e5NKQHTAhRn6bj1qmX4Px7eCbRDnBXMHI9Y6KvZAMneTrBsH


